import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => { await page.clock.install() })

test('entry asks who is playing and adult battles keep their mode through retry and menus', async ({ page }) => {
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/game/conquest')
  await expect(page.getByRole('heading', { name: '오늘은 누가 대장이 될까요?' })).toBeVisible()
  await expect(page.getByRole('button', { name: '아이 모드로 시작', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '어른 모드로 시작', exact: true })).toBeVisible()
  await expect(page.locator('.ct-team-card')).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.getByRole('button', { name: '어른 모드로 시작', exact: true }).click()
  await expect(page.locator('.ct-mode-badge')).toContainText('어른 모드')
  await page.getByRole('button', { name: '1탄 출정하기' }).click()
  await expect(page.locator('.ct-land')).toHaveCount(12)
  const troops = Number(await page.locator('.ct-land[data-owner="0"]').getAttribute('data-troops'))
  expect(troops).toBeGreaterThanOrEqual(44)
  expect(troops).toBeLessThan(50)
  await page.clock.runFor(6000)
  await expect(page.locator('.ct-fleet')).not.toHaveCount(0)
  await page.getByRole('button', { name: '이번 탄 다시 시작' }).click()
  await expect(page.locator('.ct-mode-badge')).toContainText('어른 모드')
  await expect(page.locator('.ct-battle-clock')).toContainText('0:00')
  await page.getByRole('button', { name: '팀 · 모험 고르기' }).filter({ visible: true }).click()
  await expect(page.locator('.ct-mode-badge')).toContainText('어른 모드')
  await page.getByRole('button', { name: '아이 · 어른 다시 선택', exact: true }).click()
  await page.getByRole('button', { name: '아이 모드로 시작', exact: true }).click()
  await page.getByRole('button', { name: '1탄 출정하기' }).click()
  await expect(page.locator('.ct-mode-badge')).toContainText('아이 모드')
  expect(Number(await page.locator('.ct-land[data-owner="0"]').getAttribute('data-troops'))).toBeGreaterThanOrEqual(61)
  await page.clock.runFor(3000)
  await expect(page.locator('.ct-fleet')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('legacy child progress and independent adult progress survive mode switching and reloads', async ({ page }) => {
  await page.addInitScript(() => {
    if (!localStorage.getItem('ian-conquest-v1')) localStorage.setItem('ian-conquest-v1', JSON.stringify({ selected: 3, cleared: [0, 0, 0, 12, 0, 0], stars: { '3-12': 3 } }))
    if (!localStorage.getItem('ian-conquest-adult-v1')) localStorage.setItem('ian-conquest-adult-v1', JSON.stringify({ selected: 5, cleared: [0, 0, 0, 0, 0, 19], stars: { '5-19': 2 } }))
  })
  await page.goto('/game/conquest')
  await page.getByRole('button', { name: '아이 모드로 시작', exact: true }).click()
  await expect(page.getByRole('button', { name: '13탄 출정하기' })).toBeVisible()
  await expect(page.getByRole('button', { name: '마법천자문 악당팀, 대마왕' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '아이 · 어른 다시 선택', exact: true }).click()
  await page.getByRole('button', { name: '어른 모드로 시작', exact: true }).click()
  await expect(page.getByRole('button', { name: '어벤져스팀, 아이언맨' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '20탄 출정하기' }).click()
  await expect(page.locator('.ct-land')).toHaveCount(36)
  await expect(page.locator('.ct-mode-badge')).toContainText('어른 모드')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.getByRole('button', { name: '팀 · 모험 고르기' }).filter({ visible: true }).click()
  await page.getByRole('button', { name: '마법천자문 악당팀, 대마왕' }).click()
  await expect(page.getByRole('button', { name: '1탄 출정하기' })).toBeVisible()
  await page.locator('.ct-level-picker summary').click()
  await expect(page.getByRole('button', { name: '2탄, 잠김', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('heading', { name: '오늘은 누가 대장이 될까요?' })).toBeVisible()
  await page.getByRole('button', { name: '어른 모드로 시작', exact: true }).click()
  await expect(page.getByRole('button', { name: '마법천자문 악당팀, 대마왕' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: '1탄 출정하기' })).toBeVisible()
  await page.getByRole('button', { name: '아이 · 어른 다시 선택', exact: true }).click()
  await page.getByRole('button', { name: '아이 모드로 시작', exact: true }).click()
  await expect(page.getByRole('button', { name: '13탄 출정하기' })).toBeVisible()
  const records = await page.evaluate(() => ({ child: JSON.parse(localStorage.getItem('ian-conquest-v1')), adult: JSON.parse(localStorage.getItem('ian-conquest-adult-v1')) }))
  expect(records.child.cleared).toEqual([0, 0, 0, 12, 0, 0])
  expect(records.child.stars).toEqual({ '3-12': 3 })
  expect(records.adult.cleared).toEqual([0, 0, 0, 0, 0, 19])
  expect(records.adult.stars).toEqual({ '5-19': 2 })
})

test('child clears cannot unlock adult stages', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('ian-conquest-v1', JSON.stringify({ selected: 0, cleared: [20, 20, 20, 20, 20, 20], stars: {} })))
  await page.goto('/game/conquest')
  await page.getByRole('button', { name: '어른 모드로 시작', exact: true }).click()
  await expect(page.getByRole('button', { name: '1탄 출정하기' })).toBeVisible()
  await page.locator('.ct-level-picker summary').click()
  await expect(page.getByRole('button', { name: '2탄, 잠김', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '아이 · 어른 다시 선택', exact: true }).click()
  await page.getByRole('button', { name: '아이 모드로 시작', exact: true }).click()
  await expect(page.getByRole('button', { name: '20탄 출정하기' })).toBeVisible()
})
